<?php

namespace FrontOfficeBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function  findclientbyuser($id){
        $query=$this->getEntityManager()->createQuery("SELECT c FROM FrontOfficeBundle:client c where c.user ='$id' ");
        return $query->getSingleResult();
    }
}
