<?php

namespace FrontOfficeBundle\Repository;

/**
 * Detail_PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Detail_PanierRepository extends \Doctrine\ORM\EntityRepository
{
}
