<?php

namespace FrontOfficeBundle\Repository;

/**
 * detail_commandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class detail_commandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function  findclientbyCommande($id){
        $query=$this->getEntityManager()->createQuery("SELECT c FROM FrontOfficeBundle:detail_commande c where c.Commande ='$id' ");
        return $query->getResult();
    }
}
